services:
  random-app:
    image: chentex/random-logger:latest
    container_name: random-app
    environment:
      - LOG_FREQ=1
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"

  elasticsearch:
    image: elasticsearch:9.1.3
    container_name: elasticsearch
    logging:
      driver: "local"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "/bin/bash -lc '</dev/tcp/localhost/9200'"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s
    mem_limit: "4g"

  kibana:
    image: kibana:9.1.3
    container_name: kibana
    logging:
      driver: "local"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "/bin/bash -lc '</dev/tcp/localhost/5601'"]
      interval: 10s
      timeout: 5s
      retries: 24
      start_period: 30s

  kibana-setup:
    image: curlimages/curl:8.10.1
    container_name: kibana-setup
    environment:
      - KBN_URL=http://kibana:5601
      - DATA_VIEW_TITLE=docker-logs-*
      - DATA_VIEW_NAME=Docker logs
    logging:
      driver: "local"
    command: ["/bin/sh", "/setup/kibana_setup.sh"]
    volumes:
      - ./provisioning/kibana/kibana_setup.sh:/setup/kibana_setup.sh:ro
    depends_on:
      kibana:
        condition: service_healthy

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.2
    container_name: logstash
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx256m"
    ports:
      - "12201:12201/udp"
    volumes:
      - ./provisioning/logstash/pipeline:/usr/share/logstash/pipeline:ro
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  grafana-data:
  es-data:
