services:
  mcpo:
    image: ghcr.io/open-webui/mcpo:main
    container_name: mcpo
    volumes:
      - ./provisioning/openwebui/mcpo.config.json:/config/mcpo.config.json:ro
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    command:
      [
        "--config",
        "/config/mcpo.config.json",
        "--hot-reload",
        "--api-key",
        "top-secret",
      ]
    ports:
      - "8000:8000"

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    ports:
      - "3001:8080"
    environment:
      GLOBAL_LOG_LEVEL: debug
      ENABLE_OPENAI_API: True
      OPENAI_API_BASE_URL: http://bag:80/api/v1
      OPENAI_API_KEY: bedrock
      ENABLE_PERSISTENT_CONFIG: False
      ENABLE_DIRECT_CONNECTIONS: True
      ENABLE_SIGNUP: False
      WEBUI_AUTH: False
      DEFAULT_USER_ROLE: admin
      TOOL_SERVER_CONNECTIONS: >-
        [
          {
            "url": "http://mcpo:8000/aws-mcp-cost-explorer",
            "path": "/openapi.json",
            "auth_type": "bearer",
            "key": "top-secret",
            "config": {},
            "info": { "name": "AWS Cost Explorer", "description": "AWS Cost Explorer via MCPO" }
          }
        ]
    volumes:
      - openwebui-data:/app/backend/data
    depends_on:
      mcpo:
        condition: service_started

  bag:
    image: bedrock-gateway # follow https://docs.openwebui.com/tutorials/integrations/amazon-bedrock/
    container_name: bag
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    ports:
      - "8001:80"

volumes:
  openwebui-data:
