global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'app'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['app:8081'] # internal port

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080'] # internal port
